project:
  type: website
  output-dir: docs

website:
  title: "Aiden Roach's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: example.qmd
        text: "Examples of Work"

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

